---
# Task
- name: Install the packages - {{ pkgs }}
  ansible.builtin.dnf:
    name: "{{ pkgs }}"
    state: present

- name: Start the service = {{ svcs }}
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ svcs }}"