---
- name: Restore playbook.yaml
  hosts: all
  gather_facts: false
  vars_files:
    - vars/web.yml
  tasks: 
    # 1) 방화벽 종료 - http, https 
    - name: 1) 방화벽 종료 - http, https
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop: "{{ fw_webs }}"
      ignore_errors: true
      

    # 2) 서비스 종료 - httpd, firewalld
    - name: 2) 서비스 종료 - httpd, firewalld
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop: "{{ svcs }}"
  
    - name: 3) 서비스 삭제
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html.htaccess
        - /etc/httpd/secrets
        - /var/www/html/index.html

    - name: 4) 패키지 삭제
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
        state: absent
