---
    ###############################################
    # Play 01:
    # 1) 웹서버 패키지 설치 및 서비스 기동 - include_tasks
    # 2) 방화벽 패키지 설치 및 서비스 기동, 포트 등록 - import_tasks
    # 3) 웹서버 설정(/var/www/html/index.html) - import_tasks
    # Play 02:
    # 4) 웹요청 - import_playbook
    ###############################################
- name: 0) WEB 서버 구축
  hosts: webservers
  gather_facts: true
  tasks:
    # Play 01:
    # 1) 웹서버 패키지 설치 및 서비스 기동 - include_tasks
    - name: 1) 웹서버 패키지 설치 및 서비스 기동
      ansible.builtin.include_tasks:
        file: tasks/web.yml
      vars:
        pkgs:
          - httpd
          - mod_ssl
        svcs:
          - httpd
      when: ansible_os_family == "RedHat"

    # 2) 방화벽 패키지 설치 및 서비스 기동, 포트 등록 - import_tasks
    - name: 2) 방화벽 패키지 설치 및 서비스 기동, 포트 등록
      ansible.builtin.import_tasks: tasks/fw.yml
      vars:
        pkgs:
          - firewalld
        svcs:
          - firewalld
        opens:
          - http
          - https
    # 3) 웹서버 설정(/var/www/html/index.html) - import_tasks
    - name: 3) 웹서버 설정(/var/www/html/index.html)
      ansible.builtin.import_tasks: tasks/placeholder.yml
      vars:
        file: /var/www/html/index.html

- name: 웹요청
  ansible.builtin.import_playbook: plays/test.yml
  vars:
    urls:
      - http://ansible1.example.com
      - https://ansible1.example.com