---
- name: Gather facts from all hosts
  hosts: all
  gather_facts: true
  tags: always
  tasks: []


- name: Configure DNS Server
  hosts: dns_server
  become: true
  gather_facts: false
  tags: dns
  tasks:
    - name: Configure DNS Server Role
      ansible.builtin.include_role:
        name: dns
      vars:
        dns_domain: example.com
        dns_server_hostname: "{{ hostvars.ansible.ansible_hostname }}"

        reverse_zone: 10.168.192.in-addr.arpa
        reverse_zone_file: 10.168.192.rev

        dns_zone_serial: 20260623

        dns_records:
          - name: ansible
            ip: "{{ hostvars.ansible.ansible_default_ipv4.address }}"
          - name: ansible1
            ip: "{{ hostvars.ansible1.ansible_default_ipv4.address }}"
          - name: ansible2
            ip: "{{ hostvars.ansible2.ansible_default_ipv4.address }}"
          - name: ansible3
            ip: "{{ hostvars.ansible3.ansible_default_ipv4.address }}"            
          - name: ansible4
            ip: "{{ hostvars.ansible4.ansible_default_ipv4.address }}"



- name: Configure DNS Clients
  hosts: dns_clients
  become: true
  gather_facts: false
  tags: dns_client
  tasks:
    - name: Configure DNS Client Role
      ansible.builtin.include_role:
        name: dns_client
      vars:
        dns_server_ip: "{{ hostvars.ansible.ansible_default_ipv4.address }}"
        conn_name: eth0


- name: Configure Mail
  hosts: mail
  become: true
  gather_facts: true
  tags: mail
  tasks:
    - name: Configure Mail Role
      ansible.builtin.include_role:
        name: mail
      vars:
        mail_domain: example.com


- name: Configure WEB Servers
  hosts: web_servers
  become: true
  gather_facts: true
  tags: web
  tasks:
    - name: Configure WEB Role
      ansible.builtin.include_role:
        name: web


- name: Configure FTP Servers
  hosts: ftp_servers
  become: true
  gather_facts: false
  tags: ftp
  tasks:
    - name: Configure FTP Role
      ansible.builtin.include_role:
        name: ftp