---
- name: DB 설치
  hosts: databases
  gather_facts: false
  remote_user: root
  tasks:

    # 1) DB 종료
    - name: 2) DB 종료 - mariadb
      ansible.builtin.systemd:
        name: mariadb
        state: stopped
        enabled: flase
      ignore_errors: true
  
    # 2) DB 패키지 설치 - mariadb, mariadb-server, python3-PyMySQL
    - name: 1) DB 패키지 설치 - mariadb, mariadb-server, python3-PyMySQL
      ansible.builtin.dnf:
        name:
          - mariadb
          - mariadb-server
          - python3-PyMySQL
        state: absent


