---
- name: Restore playbook.yml
  hosts: all
  vars_files:
    - vars/vars.yml
  tasks: 
    - name: 1) 방화벽 서비스 제거 - {{fw_http}}, {{fw_https}}
      ansible.posix.firewalld:
        service: "{{item}}"
        permanent: true
        immediate: true
        state: disabled
      loop:
        - "{{fw_http}}"
        - "{{fw_https}}"

    - name: 2) 서비스 설정 제거 - {{file_index}}
      ansible.builtin.get_url:
        path: "{{file_index}}"
        state: absent
      ignore_errors: true

    - name: 3) 서비스 종료 - {{svc_web}}, {{svc_fw}}
      ansible.builtin.systemd:
        name: "{{item}}"
        state: stopped
        enabled: false
      loop:
        - "{{svc_web}}"
        - "{{svc_fw}}"  

    - name: 4) 패키지 삭제 = {{ pkg_httpd }}, {{ pkg_htttps }}
      ansible.builtin.dnf:
        name:
          - "{{pkg_httpd}}"
          - "{{pkg_https}}"
        state: absent






